--
-- This script was generated by Valentina Studio
-- Application homepage: http://www.valentina-db.com/
--

-- CREATE DATABASE "chevacadb" ---------------------------------
USE master;
IF NOT EXISTS( SELECT * FROM sys.databases WHERE name = 'chevacadb' )
CREATE DATABASE chevacadb
GO

-- Change database property: AUTO_SHRINK
ALTER DATABASE [chevacadb] SET AUTO_SHRINK OFF
GO

-- Change database property: AUTO_CREATE_STATISTICS
ALTER DATABASE [chevacadb] SET AUTO_CREATE_STATISTICS ON
GO

-- Change database property: AUTO_CLOSE
ALTER DATABASE [chevacadb] SET AUTO_CLOSE ON
GO

-- Change database property: CURSOR_DEFAULT
ALTER DATABASE [chevacadb] SET CURSOR_DEFAULT GLOBAL
GO

-- Change database property: RECURSIVE_TRIGGERS
ALTER DATABASE [chevacadb] SET RECURSIVE_TRIGGERS OFF
GO

-- Change database property: CURSOR_CLOSE_ON_COMMIT
ALTER DATABASE [chevacadb] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

-- Change database property: PARAMETERIZATION
ALTER DATABASE [chevacadb] SET PARAMETERIZATION SIMPLE
GO

-- Change database property: 
ALTER DATABASE [chevacadb] SET READ_WRITE
GO

-- Change database property: DATE_CORRELATION_OPTIMIZATION
ALTER DATABASE [chevacadb] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

-- Change database property: TRUSTWORTHY
ALTER DATABASE [chevacadb] SET TRUSTWORTHY OFF
GO

-- Change database property: DB_CHAINING
ALTER DATABASE [chevacadb] SET DB_CHAINING OFF
GO

-- Change database property: QUOTED_IDENTIFIER
ALTER DATABASE [chevacadb] SET QUOTED_IDENTIFIER OFF
GO

-- Change database property: 
ALTER DATABASE [chevacadb] SET  ONLINE
GO

-- Change database property: PAGE_VERIFY
ALTER DATABASE [chevacadb] SET PAGE_VERIFY CHECKSUM
GO

-- Change database property: NUMERIC_ROUNDABORT
ALTER DATABASE [chevacadb] SET NUMERIC_ROUNDABORT OFF
GO

-- Change database property: RECOVERY
ALTER DATABASE [chevacadb] SET RECOVERY FULL
GO

-- Change database property: CONCAT_NULL_YIELDS_NULL
ALTER DATABASE [chevacadb] SET CONCAT_NULL_YIELDS_NULL OFF
GO

-- Change database property: ARITHABORT
ALTER DATABASE [chevacadb] SET ARITHABORT OFF
GO

-- Change database property: ANSI_WARNINGS
ALTER DATABASE [chevacadb] SET ANSI_WARNINGS OFF
GO

-- Change database property: COMPATIBILITY_LEVEL
ALTER DATABASE [chevacadb] SET COMPATIBILITY_LEVEL = 150
GO

-- Change database property: ANSI_PADDING
ALTER DATABASE [chevacadb] SET ANSI_PADDING OFF
GO

-- Change database property: ANSI_NULLS
ALTER DATABASE [chevacadb] SET ANSI_NULLS OFF
GO

-- Change database property: 
ALTER DATABASE [chevacadb] SET  MULTI_USER
GO

-- Change database property: ANSI_NULL_DEFAULT
ALTER DATABASE [chevacadb] SET ANSI_NULL_DEFAULT OFF
GO

-- Change database property: AUTO_UPDATE_STATISTICS_ASYNC
ALTER DATABASE [chevacadb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

-- Change database property: HONOR_BROKER_PRIORITY
ALTER DATABASE [chevacadb] SET HONOR_BROKER_PRIORITY OFF
GO

-- Change database property: AUTO_UPDATE_STATISTICS
ALTER DATABASE [chevacadb] SET AUTO_UPDATE_STATISTICS ON
GO

-- Change database property: _BROKER
ALTER DATABASE [chevacadb] SET DISABLE_BROKER
GO;
-- -------------------------------------------------------------
;

GO

USE [chevacadb];

GO
-- ---------------------------------------------------------


BEGIN TRANSACTION;

-- CREATE TABLE "Db_Ch_Devices" --------------------------------
CREATE TABLE [dbo].[Db_Ch_Devices] ( 
	[Ch_Device_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Chirpstack_Device_ID] INT NOT NULL, 
	[Chirpstack_Dev_Eui] NVARCHAR( 100 ) NOT NULL, 
	[Chirpstack_Profile] NVARCHAR( max ) NULL,
	PRIMARY KEY ( [Ch_Device_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Lands" -------------------------------------
CREATE TABLE [dbo].[Db_Lands] ( 
	[Ranch_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Ch_Organization_ID] INT NOT NULL, 
	[Company_Rut] NVARCHAR( 20 ) NOT NULL, 
	[Company_Name] NVARCHAR( max ) NULL, 
	[Company_Domain] NVARCHAR( 50 ) NOT NULL, 
	[Company_Rsocial] NVARCHAR( 50 ) NOT NULL, 
	[Company_Logo] NVARCHAR( max ) NULL,
	PRIMARY KEY ( [Ranch_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_List_Animals_Breeds" -----------------------
CREATE TABLE [dbo].[Db_List_Animals_Breeds] ( 
	[List_animals_breeds_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Breed_code] INT NOT NULL, 
	[Breed_name] NVARCHAR( 30 ) NOT NULL, 
	[Breed_group] NVARCHAR( 30 ) NOT NULL,
	PRIMARY KEY ( [List_animals_breeds_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_List_Animals_Categories" -------------------
CREATE TABLE [dbo].[Db_List_Animals_Categories] ( 
	[List_animals_categories_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Category_code] INT NOT NULL, 
	[Category_name] NVARCHAR( 30 ) NOT NULL, 
	[Category_group] NVARCHAR( 30 ) NOT NULL,
	PRIMARY KEY ( [List_animals_categories_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_List_Animals_Types" ------------------------
CREATE TABLE [dbo].[Db_List_Animals_Types] ( 
	[List_animals_type_ID] INT NOT NULL, 
	[Type_code] INT NOT NULL, 
	[Type_name] NVARCHAR( 30 ) NOT NULL, 
	[Type_group] NVARCHAR( 30 ) NOT NULL,
	PRIMARY KEY ( [List_animals_type_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Mgap_Tags" ---------------------------------
CREATE TABLE [dbo].[Db_Mgap_Tags] ( 
	[MGAP_Tag_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[MGAP_Key] NVARCHAR( 50 ) NULL, 
	[Description] NVARCHAR( max ) NULL,
	PRIMARY KEY ( [MGAP_Tag_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Roles" -------------------------------------
CREATE TABLE [dbo].[Db_Roles] ( 
	[Rol_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Rol_Name] NVARCHAR( 50 ) NOT NULL, 
	[Description] NVARCHAR( max ) NULL,
	PRIMARY KEY ( [Rol_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Land_Farms" --------------------------------
CREATE TABLE [dbo].[Db_Land_Farms] ( 
	[Land_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Chirpstack_App_ID] NVARCHAR( 50 ) NOT NULL, 
	[Land_Name] NVARCHAR( 50 ) NOT NULL, 
	[Ranch_ID] INT NOT NULL, 
	[Ranch_ID1] INT NULL, 
	[Description] NVARCHAR( max ) NULL,
	PRIMARY KEY ( [Land_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Land_Farms_Ranch_ID1" -------------------
CREATE  INDEX [IX_Db_Land_Farms_Ranch_ID1] ON [dbo].[Db_Land_Farms]( [Ranch_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Users" -------------------------------------
CREATE TABLE [dbo].[Db_Users] ( 
	[User_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Person_ID] INT NOT NULL, 
	[Rol_ID] INT NOT NULL, 
	[Rol_ID1] INT NULL, 
	[User_Name] NVARCHAR( 100 ) NOT NULL, 
	[Password] NVARCHAR( max ) NULL, 
	[Image_Url] NVARCHAR( max ) NULL,
	PRIMARY KEY ( [User_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Users_Rol_ID1" --------------------------
CREATE  INDEX [IX_Db_Users_Rol_ID1] ON [dbo].[Db_Users]( [Rol_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Animals" -----------------------------------
CREATE TABLE [dbo].[Db_Animals] ( 
	[Animal_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL, 
	[Ch_Device_ID] INT NOT NULL, 
	[Ch_Device_ID1] INT NULL, 
	[MGAP_Tag_ID] INT NOT NULL, 
	[MGAP_Tag_ID1] INT NULL, 
	[List_animals_types_code] INT NOT NULL, 
	[List_animals_breeds_code] INT NOT NULL, 
	[List_animals_categories_code] INT NOT NULL, 
	[Code_Animal] INT NOT NULL, 
	[Gender_MF] NVARCHAR( 1 ) NOT NULL, 
	[Date_Born] DATETIME2 NULL,
	PRIMARY KEY ( [Animal_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Animals_Ch_Device_ID1" ------------------
CREATE  INDEX [IX_Db_Animals_Ch_Device_ID1] ON [dbo].[Db_Animals]( [Ch_Device_ID1] ASC )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Animals_Land_ID1" -----------------------
CREATE  INDEX [IX_Db_Animals_Land_ID1] ON [dbo].[Db_Animals]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Animals_MGAP_Tag_ID1" -------------------
CREATE  INDEX [IX_Db_Animals_MGAP_Tag_ID1] ON [dbo].[Db_Animals]( [MGAP_Tag_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Land_Feeders" ------------------------------
CREATE TABLE [dbo].[Db_Land_Feeders] ( 
	[Land_farm_feeder_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL,
	PRIMARY KEY ( [Land_farm_feeder_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Land_Feeders_Land_ID1" ------------------
CREATE  INDEX [IX_Db_Land_Feeders_Land_ID1] ON [dbo].[Db_Land_Feeders]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Land_Roosts" -------------------------------
CREATE TABLE [dbo].[Db_Land_Roosts] ( 
	[Land_farm_roost_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL,
	PRIMARY KEY ( [Land_farm_roost_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Land_Roosts_Land_ID1" -------------------
CREATE  INDEX [IX_Db_Land_Roosts_Land_ID1] ON [dbo].[Db_Land_Roosts]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Land_Troughs" ------------------------------
CREATE TABLE [dbo].[Db_Land_Troughs] ( 
	[Land_farm_trough_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL,
	PRIMARY KEY ( [Land_farm_trough_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Land_Troughs_Land_ID1" ------------------
CREATE  INDEX [IX_Db_Land_Troughs_Land_ID1] ON [dbo].[Db_Land_Troughs]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Employees" ---------------------------------
CREATE TABLE [dbo].[Db_Employees] ( 
	[Person_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Full_Name] NVARCHAR( max ) NULL, 
	[Email] NVARCHAR( max ) NULL, 
	[Identification] NVARCHAR( max ) NULL, 
	[Date_born] DATETIME2 NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL, 
	[User_ID] INT NOT NULL, 
	[IsOwner] BIT NOT NULL, 
	[Ranch_ID] INT NULL,
	PRIMARY KEY ( [Person_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Employees_Land_ID1" ---------------------
CREATE  INDEX [IX_Db_Employees_Land_ID1] ON [dbo].[Db_Employees]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Employees_Ranch_ID" ---------------------
CREATE  INDEX [IX_Db_Employees_Ranch_ID] ON [dbo].[Db_Employees]( [Ranch_ID] ASC )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Employees_User_ID" ----------------------
CREATE  UNIQUE  INDEX [IX_Db_Employees_User_ID] ON [dbo].[Db_Employees]( [User_ID] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Logs" --------------------------------------
CREATE TABLE [dbo].[Db_Logs] ( 
	[Log_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Date_created] DATETIME2 NOT NULL, 
	[User_ID] INT NOT NULL, 
	[User_ID1] INT NULL, 
	[IP_client] NVARCHAR( 20 ) NOT NULL, 
	[Description] NVARCHAR( 100 ) NOT NULL, 
	[Info] NVARCHAR( 150 ) NOT NULL,
	PRIMARY KEY ( [Log_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Logs_User_ID1" --------------------------
CREATE  INDEX [IX_Db_Logs_User_ID1] ON [dbo].[Db_Logs]( [User_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Animal_Cows" -------------------------------
CREATE TABLE [dbo].[Db_Animal_Cows] ( 
	[Animal_Cow_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NULL,
	PRIMARY KEY ( [Animal_Cow_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Animal_Cows_Animal_ID" ------------------
CREATE  INDEX [IX_Db_Animal_Cows_Animal_ID] ON [dbo].[Db_Animal_Cows]( [Animal_ID] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Animal_Horses" -----------------------------
CREATE TABLE [dbo].[Db_Animal_Horses] ( 
	[Animal_Horse_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NULL,
	PRIMARY KEY ( [Animal_Horse_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Animal_Horses_Animal_ID" ----------------
CREATE  INDEX [IX_Db_Animal_Horses_Animal_ID] ON [dbo].[Db_Animal_Horses]( [Animal_ID] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Animal_Sheeps" -----------------------------
CREATE TABLE [dbo].[Db_Animal_Sheeps] ( 
	[Animal_Sheep_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NULL,
	PRIMARY KEY ( [Animal_Sheep_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Animal_Sheeps_Animal_ID" ----------------
CREATE  INDEX [IX_Db_Animal_Sheeps_Animal_ID] ON [dbo].[Db_Animal_Sheeps]( [Animal_ID] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_History_Animals_Diseases" ------------------
CREATE TABLE [dbo].[Db_History_Animals_Diseases] ( 
	[History_animals_diseases_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NOT NULL, 
	[Animal_ID1] INT NULL,
	PRIMARY KEY ( [History_animals_diseases_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_History_Animals_Diseases_Animal_ID1" ----
CREATE  INDEX [IX_Db_History_Animals_Diseases_Animal_ID1] ON [dbo].[Db_History_Animals_Diseases]( [Animal_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_History_Animals_Vaccines" ------------------
CREATE TABLE [dbo].[Db_History_Animals_Vaccines] ( 
	[History_animals_vaccines_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NOT NULL, 
	[Animal_ID1] INT NULL,
	PRIMARY KEY ( [History_animals_vaccines_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_History_Animals_Vaccines_Animal_ID1" ----
CREATE  INDEX [IX_Db_History_Animals_Vaccines_Animal_ID1] ON [dbo].[Db_History_Animals_Vaccines]( [Animal_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

SET IDENTITY_INSERT [dbo].[Db_Ch_Devices] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Ch_Devices] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Lands] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Lands] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_List_Animals_Breeds] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_List_Animals_Breeds] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_List_Animals_Categories] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_List_Animals_Categories] OFF
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Mgap_Tags] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Mgap_Tags] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Roles] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Roles] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Land_Farms] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Land_Farms] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Users] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Users] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Animals] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Animals] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Land_Feeders] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Land_Feeders] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Land_Roosts] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Land_Roosts] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Land_Troughs] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Land_Troughs] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Employees] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Employees] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Logs] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Logs] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Animal_Cows] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Animal_Cows] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Animal_Horses] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Animal_Horses] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Animal_Sheeps] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Animal_Sheeps] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_History_Animals_Diseases] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_History_Animals_Diseases] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_History_Animals_Vaccines] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_History_Animals_Vaccines] OFF
GO
BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Animals_Db_Ch_Devices_Ch_Device_ID1" -----
ALTER TABLE [dbo].[Db_Animals]
	ADD CONSTRAINT [FK_Db_Animals_Db_Ch_Devices_Ch_Device_ID1]
	FOREIGN KEY ([Ch_Device_ID1])
	REFERENCES [dbo].[Db_Ch_Devices]( [Ch_Device_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Land_Farms_Db_Lands_Ranch_ID1" -----------
ALTER TABLE [dbo].[Db_Land_Farms]
	ADD CONSTRAINT [FK_Db_Land_Farms_Db_Lands_Ranch_ID1]
	FOREIGN KEY ([Ranch_ID1])
	REFERENCES [dbo].[Db_Lands]( [Ranch_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Employees_Db_Lands_Ranch_ID" -------------
ALTER TABLE [dbo].[Db_Employees]
	ADD CONSTRAINT [FK_Db_Employees_Db_Lands_Ranch_ID]
	FOREIGN KEY ([Ranch_ID])
	REFERENCES [dbo].[Db_Lands]( [Ranch_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Animals_Db_Mgap_Tags_MGAP_Tag_ID1" -------
ALTER TABLE [dbo].[Db_Animals]
	ADD CONSTRAINT [FK_Db_Animals_Db_Mgap_Tags_MGAP_Tag_ID1]
	FOREIGN KEY ([MGAP_Tag_ID1])
	REFERENCES [dbo].[Db_Mgap_Tags]( [MGAP_Tag_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Users_Db_Roles_Rol_ID1" ------------------
ALTER TABLE [dbo].[Db_Users]
	ADD CONSTRAINT [FK_Db_Users_Db_Roles_Rol_ID1]
	FOREIGN KEY ([Rol_ID1])
	REFERENCES [dbo].[Db_Roles]( [Rol_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Animals_Db_Land_Farms_Land_ID1" ----------
ALTER TABLE [dbo].[Db_Animals]
	ADD CONSTRAINT [FK_Db_Animals_Db_Land_Farms_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Db_Land_Farms]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Land_Feeders_Db_Land_Farms_Land_ID1" -----
ALTER TABLE [dbo].[Db_Land_Feeders]
	ADD CONSTRAINT [FK_Db_Land_Feeders_Db_Land_Farms_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Db_Land_Farms]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Land_Roosts_Db_Land_Farms_Land_ID1" ------
ALTER TABLE [dbo].[Db_Land_Roosts]
	ADD CONSTRAINT [FK_Db_Land_Roosts_Db_Land_Farms_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Db_Land_Farms]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Land_Troughs_Db_Land_Farms_Land_ID1" -----
ALTER TABLE [dbo].[Db_Land_Troughs]
	ADD CONSTRAINT [FK_Db_Land_Troughs_Db_Land_Farms_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Db_Land_Farms]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Employees_Db_Land_Farms_Land_ID1" --------
ALTER TABLE [dbo].[Db_Employees]
	ADD CONSTRAINT [FK_Db_Employees_Db_Land_Farms_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Db_Land_Farms]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Employees_Db_Users_User_ID" --------------
ALTER TABLE [dbo].[Db_Employees]
	ADD CONSTRAINT [FK_Db_Employees_Db_Users_User_ID]
	FOREIGN KEY ([User_ID])
	REFERENCES [dbo].[Db_Users]( [User_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Logs_Db_Users_User_ID1" ------------------
ALTER TABLE [dbo].[Db_Logs]
	ADD CONSTRAINT [FK_Db_Logs_Db_Users_User_ID1]
	FOREIGN KEY ([User_ID1])
	REFERENCES [dbo].[Db_Users]( [User_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Animal_Cows_Db_Animals_Animal_ID" --------
ALTER TABLE [dbo].[Db_Animal_Cows]
	ADD CONSTRAINT [FK_Db_Animal_Cows_Db_Animals_Animal_ID]
	FOREIGN KEY ([Animal_ID])
	REFERENCES [dbo].[Db_Animals]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Animal_Horses_Db_Animals_Animal_ID" ------
ALTER TABLE [dbo].[Db_Animal_Horses]
	ADD CONSTRAINT [FK_Db_Animal_Horses_Db_Animals_Animal_ID]
	FOREIGN KEY ([Animal_ID])
	REFERENCES [dbo].[Db_Animals]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Animal_Sheeps_Db_Animals_Animal_ID" ------
ALTER TABLE [dbo].[Db_Animal_Sheeps]
	ADD CONSTRAINT [FK_Db_Animal_Sheeps_Db_Animals_Animal_ID]
	FOREIGN KEY ([Animal_ID])
	REFERENCES [dbo].[Db_Animals]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_History_Animals_Diseases_Db_Animals_Animal_ID1" 
ALTER TABLE [dbo].[Db_History_Animals_Diseases]
	ADD CONSTRAINT [FK_Db_History_Animals_Diseases_Db_Animals_Animal_ID1]
	FOREIGN KEY ([Animal_ID1])
	REFERENCES [dbo].[Db_Animals]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_History_Animals_Vaccines_Db_Animals_Animal_ID1" 
ALTER TABLE [dbo].[Db_History_Animals_Vaccines]
	ADD CONSTRAINT [FK_Db_History_Animals_Vaccines_Db_Animals_Animal_ID1]
	FOREIGN KEY ([Animal_ID1])
	REFERENCES [dbo].[Db_Animals]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

