--
-- This script was generated by Valentina Studio
-- Application homepage: http://www.valentina-db.com/
--

-- CREATE DATABASE "chevacadb" ---------------------------------
USE master;
IF NOT EXISTS( SELECT * FROM sys.databases WHERE name = 'chevacadb' )
CREATE DATABASE chevacadb
GO

-- Change database property: AUTO_SHRINK
ALTER DATABASE [chevacadb] SET AUTO_SHRINK OFF
GO

-- Change database property: AUTO_CREATE_STATISTICS
ALTER DATABASE [chevacadb] SET AUTO_CREATE_STATISTICS ON
GO

-- Change database property: AUTO_CLOSE
ALTER DATABASE [chevacadb] SET AUTO_CLOSE ON
GO

-- Change database property: CURSOR_DEFAULT
ALTER DATABASE [chevacadb] SET CURSOR_DEFAULT GLOBAL
GO

-- Change database property: RECURSIVE_TRIGGERS
ALTER DATABASE [chevacadb] SET RECURSIVE_TRIGGERS OFF
GO

-- Change database property: CURSOR_CLOSE_ON_COMMIT
ALTER DATABASE [chevacadb] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

-- Change database property: PARAMETERIZATION
ALTER DATABASE [chevacadb] SET PARAMETERIZATION SIMPLE
GO

-- Change database property: 
ALTER DATABASE [chevacadb] SET READ_WRITE
GO

-- Change database property: DATE_CORRELATION_OPTIMIZATION
ALTER DATABASE [chevacadb] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

-- Change database property: TRUSTWORTHY
ALTER DATABASE [chevacadb] SET TRUSTWORTHY OFF
GO

-- Change database property: DB_CHAINING
ALTER DATABASE [chevacadb] SET DB_CHAINING OFF
GO

-- Change database property: QUOTED_IDENTIFIER
ALTER DATABASE [chevacadb] SET QUOTED_IDENTIFIER OFF
GO

-- Change database property: 
ALTER DATABASE [chevacadb] SET  ONLINE
GO

-- Change database property: PAGE_VERIFY
ALTER DATABASE [chevacadb] SET PAGE_VERIFY CHECKSUM
GO

-- Change database property: NUMERIC_ROUNDABORT
ALTER DATABASE [chevacadb] SET NUMERIC_ROUNDABORT OFF
GO

-- Change database property: RECOVERY
ALTER DATABASE [chevacadb] SET RECOVERY FULL
GO

-- Change database property: CONCAT_NULL_YIELDS_NULL
ALTER DATABASE [chevacadb] SET CONCAT_NULL_YIELDS_NULL OFF
GO

-- Change database property: ARITHABORT
ALTER DATABASE [chevacadb] SET ARITHABORT OFF
GO

-- Change database property: ANSI_WARNINGS
ALTER DATABASE [chevacadb] SET ANSI_WARNINGS OFF
GO

-- Change database property: COMPATIBILITY_LEVEL
ALTER DATABASE [chevacadb] SET COMPATIBILITY_LEVEL = 150
GO

-- Change database property: ANSI_PADDING
ALTER DATABASE [chevacadb] SET ANSI_PADDING OFF
GO

-- Change database property: ANSI_NULLS
ALTER DATABASE [chevacadb] SET ANSI_NULLS OFF
GO

-- Change database property: 
ALTER DATABASE [chevacadb] SET  MULTI_USER
GO

-- Change database property: ANSI_NULL_DEFAULT
ALTER DATABASE [chevacadb] SET ANSI_NULL_DEFAULT OFF
GO

-- Change database property: AUTO_UPDATE_STATISTICS_ASYNC
ALTER DATABASE [chevacadb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

-- Change database property: HONOR_BROKER_PRIORITY
ALTER DATABASE [chevacadb] SET HONOR_BROKER_PRIORITY OFF
GO

-- Change database property: AUTO_UPDATE_STATISTICS
ALTER DATABASE [chevacadb] SET AUTO_UPDATE_STATISTICS ON
GO

-- Change database property: _BROKER
ALTER DATABASE [chevacadb] SET DISABLE_BROKER
GO;
-- -------------------------------------------------------------
;

GO

USE [chevacadb];

GO
-- ---------------------------------------------------------


BEGIN TRANSACTION;

-- CREATE TABLE "Ch_Device" ------------------------------------
CREATE TABLE [dbo].[Ch_Device] ( 
	[Ch_Device_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Chirpstack_Device_ID] INT NOT NULL, 
	[Chirpstack_Dev_Eui] VARCHAR( 100 ) NOT NULL, 
	[Chirpstack_Profile] VARCHAR( 1 ) NULL,
	PRIMARY KEY ( [Ch_Device_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "list_animals_breeds" --------------------------
CREATE TABLE [dbo].[list_animals_breeds] ( 
	[List_animals_breeds_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Breed_code] INT NOT NULL, 
	[Breed_name] VARCHAR( 30 ) NOT NULL, 
	[Breed_group] VARCHAR( 30 ) NOT NULL,
	PRIMARY KEY ( [List_animals_breeds_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "list_animals_categories" ----------------------
CREATE TABLE [dbo].[list_animals_categories] ( 
	[List_animals_categories_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Category_code] INT NOT NULL, 
	[Category_name] VARCHAR( 30 ) NOT NULL, 
	[Category_group] VARCHAR( 30 ) NOT NULL,
	PRIMARY KEY ( [List_animals_categories_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "list_animals_types" ---------------------------
CREATE TABLE [dbo].[list_animals_types] ( 
	[List_animals_type_ID] INT NOT NULL, 
	[Type_code] INT NOT NULL, 
	[Type_name] VARCHAR( 30 ) NOT NULL, 
	[Type_group] VARCHAR( 30 ) NOT NULL,
	PRIMARY KEY ( [List_animals_type_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "MGAP_Tag" -------------------------------------
CREATE TABLE [dbo].[MGAP_Tag] ( 
	[MGAP_Tag_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[MGAP_Key] VARCHAR( 50 ) NULL, 
	[Description] VARCHAR( 1 ) NULL,
	PRIMARY KEY ( [MGAP_Tag_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Ranch" ----------------------------------------
CREATE TABLE [dbo].[Ranch] ( 
	[Ranch_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Ch_Organization_ID] INT NOT NULL, 
	[Company_Rut] VARCHAR( 20 ) NOT NULL, 
	[Company_Name] VARCHAR( 1 ) NULL, 
	[Company_Domain] VARCHAR( 50 ) NOT NULL, 
	[Company_Rsocial] VARCHAR( 50 ) NOT NULL, 
	[Company_Logo] VARCHAR( 1 ) NULL,
	PRIMARY KEY ( [Ranch_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Rol" ------------------------------------------
CREATE TABLE [dbo].[Rol] ( 
	[Rol_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Rol_Name] VARCHAR( 50 ) NOT NULL, 
	[Description] VARCHAR( 1 ) NULL,
	PRIMARY KEY ( [Rol_ID] ) )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Land" -----------------------------------------
CREATE TABLE [dbo].[Land] ( 
	[Land_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Chirpstack_App_ID] VARCHAR( 50 ) NOT NULL, 
	[Land_Name] VARCHAR( 50 ) NOT NULL, 
	[Ranch_ID] INT NOT NULL, 
	[Ranch_ID1] INT NULL, 
	[Description] VARCHAR( 1 ) NULL,
	PRIMARY KEY ( [Land_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Land_Ranch_ID1" ----------------------------
CREATE  INDEX [IX_Land_Ranch_ID1] ON [dbo].[Land]( [Ranch_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "User" -----------------------------------------
CREATE TABLE [dbo].[User] ( 
	[User_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Person_ID] INT NOT NULL, 
	[Rol_ID] INT NOT NULL, 
	[Rol_ID1] INT NULL, 
	[User_Name] VARCHAR( 100 ) NOT NULL, 
	[Password] VARCHAR( 1 ) NULL, 
	[Image_Url] VARCHAR( 1 ) NULL,
	PRIMARY KEY ( [User_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_User_Rol_ID1" ------------------------------
CREATE  INDEX [IX_User_Rol_ID1] ON [dbo].[User]( [Rol_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Animal" ---------------------------------------
CREATE TABLE [dbo].[Animal] ( 
	[Animal_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL, 
	[Ch_Device_ID] INT NOT NULL, 
	[Ch_Device_ID1] INT NULL, 
	[MGAP_Tag_ID] INT NOT NULL, 
	[MGAP_Tag_ID1] INT NULL, 
	[List_animals_types_code] INT NOT NULL, 
	[List_animals_breeds_code] INT NOT NULL, 
	[List_animals_categories_code] INT NOT NULL, 
	[Code_Animal] INT NOT NULL, 
	[Gender_MF] VARCHAR( 1 ) NOT NULL, 
	[Date_Born] DATETIME2 NULL,
	PRIMARY KEY ( [Animal_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Animal_Ch_Device_ID1" ----------------------
CREATE  INDEX [IX_Animal_Ch_Device_ID1] ON [dbo].[Animal]( [Ch_Device_ID1] ASC )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Animal_Land_ID1" ---------------------------
CREATE  INDEX [IX_Animal_Land_ID1] ON [dbo].[Animal]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Animal_MGAP_Tag_ID1" -----------------------
CREATE  INDEX [IX_Animal_MGAP_Tag_ID1] ON [dbo].[Animal]( [MGAP_Tag_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Land_Feeder" ----------------------------------
CREATE TABLE [dbo].[Land_Feeder] ( 
	[Land_farm_feeder_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL,
	PRIMARY KEY ( [Land_farm_feeder_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Land_Feeder_Land_ID1" ----------------------
CREATE  INDEX [IX_Land_Feeder_Land_ID1] ON [dbo].[Land_Feeder]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Land_Roost" -----------------------------------
CREATE TABLE [dbo].[Land_Roost] ( 
	[Land_farm_roost_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL,
	PRIMARY KEY ( [Land_farm_roost_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Land_Roost_Land_ID1" -----------------------
CREATE  INDEX [IX_Land_Roost_Land_ID1] ON [dbo].[Land_Roost]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Land_Trough" ----------------------------------
CREATE TABLE [dbo].[Land_Trough] ( 
	[Land_farm_trough_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL,
	PRIMARY KEY ( [Land_farm_trough_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Land_Trough_Land_ID1" ----------------------
CREATE  INDEX [IX_Land_Trough_Land_ID1] ON [dbo].[Land_Trough]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Logs" -----------------------------------------
CREATE TABLE [dbo].[Logs] ( 
	[Log_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Date_created] DATETIME2 NOT NULL, 
	[User_ID] INT NOT NULL, 
	[User_ID1] INT NULL, 
	[IP_client] VARCHAR( 20 ) NOT NULL, 
	[Description] VARCHAR( 100 ) NOT NULL, 
	[Info] VARCHAR( 150 ) NOT NULL,
	PRIMARY KEY ( [Log_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Logs_User_ID1" -----------------------------
CREATE  INDEX [IX_Logs_User_ID1] ON [dbo].[Logs]( [User_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Person" ---------------------------------------
CREATE TABLE [dbo].[Person] ( 
	[Person_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Full_Name] VARCHAR( 1 ) NULL, 
	[Email] VARCHAR( 1 ) NULL, 
	[Identification] VARCHAR( 1 ) NULL, 
	[Date_born] DATETIME2 NULL, 
	[Land_ID] INT NOT NULL, 
	[Land_ID1] INT NULL, 
	[User_ID] INT NOT NULL, 
	[IsOwner] BIT NOT NULL, 
	[Ranch_ID] INT NULL,
	PRIMARY KEY ( [Person_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Person_Land_ID1" ---------------------------
CREATE  INDEX [IX_Person_Land_ID1] ON [dbo].[Person]( [Land_ID1] ASC )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Person_Ranch_ID" ---------------------------
CREATE  INDEX [IX_Person_Ranch_ID] ON [dbo].[Person]( [Ranch_ID] ASC )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Person_User_ID" ----------------------------
CREATE  UNIQUE  INDEX [IX_Person_User_ID] ON [dbo].[Person]( [User_ID] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Animal_Horse" ---------------------------------
CREATE TABLE [dbo].[Animal_Horse] ( 
	[Animal_Horse_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NULL,
	PRIMARY KEY ( [Animal_Horse_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Animal_Horse_Animal_ID" --------------------
CREATE  INDEX [IX_Animal_Horse_Animal_ID] ON [dbo].[Animal_Horse]( [Animal_ID] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Animal_Sheep" ---------------------------------
CREATE TABLE [dbo].[Animal_Sheep] ( 
	[Animal_Sheep_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NULL,
	PRIMARY KEY ( [Animal_Sheep_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Animal_Sheep_Animal_ID" --------------------
CREATE  INDEX [IX_Animal_Sheep_Animal_ID] ON [dbo].[Animal_Sheep]( [Animal_ID] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "Db_Animal_Cows" -------------------------------
CREATE TABLE [dbo].[Db_Animal_Cows] ( 
	[Animal_Cow_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NULL,
	PRIMARY KEY ( [Animal_Cow_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_Db_Animal_Cows_Animal_ID" ------------------
CREATE  INDEX [IX_Db_Animal_Cows_Animal_ID] ON [dbo].[Db_Animal_Cows]( [Animal_ID] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "History_Animal_Disease" -----------------------
CREATE TABLE [dbo].[History_Animal_Disease] ( 
	[History_animals_diseases_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NOT NULL, 
	[Animal_ID1] INT NULL,
	PRIMARY KEY ( [History_animals_diseases_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_History_Animal_Disease_Animal_ID1" ---------
CREATE  INDEX [IX_History_Animal_Disease_Animal_ID1] ON [dbo].[History_Animal_Disease]( [Animal_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE TABLE "History_animal_vaccine" -----------------------
CREATE TABLE [dbo].[History_animal_vaccine] ( 
	[History_animals_vaccines_ID] INT IDENTITY ( 1, 1 )  NOT NULL, 
	[Animal_ID] INT NOT NULL, 
	[Animal_ID1] INT NULL,
	PRIMARY KEY ( [History_animals_vaccines_ID] ) )
GO;
-- -------------------------------------------------------------

-- CREATE INDEX "IX_History_animal_vaccine_Animal_ID1" ---------
CREATE  INDEX [IX_History_animal_vaccine_Animal_ID1] ON [dbo].[History_animal_vaccine]( [Animal_ID1] ASC )
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

SET IDENTITY_INSERT [dbo].[Ch_Device] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Ch_Device] OFF
GO
SET IDENTITY_INSERT [dbo].[list_animals_breeds] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[list_animals_breeds] OFF
GO
SET IDENTITY_INSERT [dbo].[list_animals_categories] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[list_animals_categories] OFF
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[MGAP_Tag] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[MGAP_Tag] OFF
GO
SET IDENTITY_INSERT [dbo].[Ranch] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Ranch] OFF
GO
SET IDENTITY_INSERT [dbo].[Rol] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Rol] OFF
GO
SET IDENTITY_INSERT [dbo].[Land] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Land] OFF
GO
SET IDENTITY_INSERT [dbo].[User] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[User] OFF
GO
SET IDENTITY_INSERT [dbo].[Animal] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Animal] OFF
GO
SET IDENTITY_INSERT [dbo].[Land_Feeder] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Land_Feeder] OFF
GO
SET IDENTITY_INSERT [dbo].[Land_Roost] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Land_Roost] OFF
GO
SET IDENTITY_INSERT [dbo].[Land_Trough] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Land_Trough] OFF
GO
SET IDENTITY_INSERT [dbo].[Logs] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Logs] OFF
GO
SET IDENTITY_INSERT [dbo].[Person] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Person] OFF
GO
SET IDENTITY_INSERT [dbo].[Animal_Horse] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Animal_Horse] OFF
GO
SET IDENTITY_INSERT [dbo].[Animal_Sheep] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Animal_Sheep] OFF
GO
SET IDENTITY_INSERT [dbo].[Db_Animal_Cows] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[Db_Animal_Cows] OFF
GO
SET IDENTITY_INSERT [dbo].[History_Animal_Disease] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[History_Animal_Disease] OFF
GO
SET IDENTITY_INSERT [dbo].[History_animal_vaccine] ON
GO
BEGIN TRANSACTION;

COMMIT TRANSACTION;

GO

SET IDENTITY_INSERT [dbo].[History_animal_vaccine] OFF
GO
BEGIN TRANSACTION;

-- CREATE LINK "FK_Animal_Ch_Device_Ch_Device_ID1" -------------
ALTER TABLE [dbo].[Animal]
	ADD CONSTRAINT [FK_Animal_Ch_Device_Ch_Device_ID1]
	FOREIGN KEY ([Ch_Device_ID1])
	REFERENCES [dbo].[Ch_Device]( [Ch_Device_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Animal_MGAP_Tag_MGAP_Tag_ID1" ---------------
ALTER TABLE [dbo].[Animal]
	ADD CONSTRAINT [FK_Animal_MGAP_Tag_MGAP_Tag_ID1]
	FOREIGN KEY ([MGAP_Tag_ID1])
	REFERENCES [dbo].[MGAP_Tag]( [MGAP_Tag_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Land_Ranch_Ranch_ID1" -----------------------
ALTER TABLE [dbo].[Land]
	ADD CONSTRAINT [FK_Land_Ranch_Ranch_ID1]
	FOREIGN KEY ([Ranch_ID1])
	REFERENCES [dbo].[Ranch]( [Ranch_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Person_Ranch_Ranch_ID" ----------------------
ALTER TABLE [dbo].[Person]
	ADD CONSTRAINT [FK_Person_Ranch_Ranch_ID]
	FOREIGN KEY ([Ranch_ID])
	REFERENCES [dbo].[Ranch]( [Ranch_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_User_Rol_Rol_ID1" ---------------------------
ALTER TABLE [dbo].[User]
	ADD CONSTRAINT [FK_User_Rol_Rol_ID1]
	FOREIGN KEY ([Rol_ID1])
	REFERENCES [dbo].[Rol]( [Rol_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Animal_Land_Land_ID1" -----------------------
ALTER TABLE [dbo].[Animal]
	ADD CONSTRAINT [FK_Animal_Land_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Land]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Land_Feeder_Land_Land_ID1" ------------------
ALTER TABLE [dbo].[Land_Feeder]
	ADD CONSTRAINT [FK_Land_Feeder_Land_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Land]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Land_Roost_Land_Land_ID1" -------------------
ALTER TABLE [dbo].[Land_Roost]
	ADD CONSTRAINT [FK_Land_Roost_Land_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Land]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Land_Trough_Land_Land_ID1" ------------------
ALTER TABLE [dbo].[Land_Trough]
	ADD CONSTRAINT [FK_Land_Trough_Land_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Land]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Person_Land_Land_ID1" -----------------------
ALTER TABLE [dbo].[Person]
	ADD CONSTRAINT [FK_Person_Land_Land_ID1]
	FOREIGN KEY ([Land_ID1])
	REFERENCES [dbo].[Land]( [Land_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Logs_User_User_ID1" -------------------------
ALTER TABLE [dbo].[Logs]
	ADD CONSTRAINT [FK_Logs_User_User_ID1]
	FOREIGN KEY ([User_ID1])
	REFERENCES [dbo].[User]( [User_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Person_User_User_ID" ------------------------
ALTER TABLE [dbo].[Person]
	ADD CONSTRAINT [FK_Person_User_User_ID]
	FOREIGN KEY ([User_ID])
	REFERENCES [dbo].[User]( [User_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Animal_Horse_Animal_Animal_ID" --------------
ALTER TABLE [dbo].[Animal_Horse]
	ADD CONSTRAINT [FK_Animal_Horse_Animal_Animal_ID]
	FOREIGN KEY ([Animal_ID])
	REFERENCES [dbo].[Animal]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Animal_Sheep_Animal_Animal_ID" --------------
ALTER TABLE [dbo].[Animal_Sheep]
	ADD CONSTRAINT [FK_Animal_Sheep_Animal_Animal_ID]
	FOREIGN KEY ([Animal_ID])
	REFERENCES [dbo].[Animal]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_Db_Animal_Cows_Animal_Animal_ID" ------------
ALTER TABLE [dbo].[Db_Animal_Cows]
	ADD CONSTRAINT [FK_Db_Animal_Cows_Animal_Animal_ID]
	FOREIGN KEY ([Animal_ID])
	REFERENCES [dbo].[Animal]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_History_Animal_Disease_Animal_Animal_ID1" ---
ALTER TABLE [dbo].[History_Animal_Disease]
	ADD CONSTRAINT [FK_History_Animal_Disease_Animal_Animal_ID1]
	FOREIGN KEY ([Animal_ID1])
	REFERENCES [dbo].[Animal]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

BEGIN TRANSACTION;

-- CREATE LINK "FK_History_animal_vaccine_Animal_Animal_ID1" ---
ALTER TABLE [dbo].[History_animal_vaccine]
	ADD CONSTRAINT [FK_History_animal_vaccine_Animal_Animal_ID1]
	FOREIGN KEY ([Animal_ID1])
	REFERENCES [dbo].[Animal]( [Animal_ID] )
	ON DELETE No Action
	ON UPDATE No Action
GO;
-- -------------------------------------------------------------

COMMIT TRANSACTION;
GO

